const CSS = `
:root{color-scheme:dark;font-family:Arial,"Noto Sans Hebrew",sans-serif;background:#071426;color:#f8fafc}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 15% 85%,#351b53 0,transparent 30%),radial-gradient(circle at 80% 10%,#102c50 0,transparent 35%),#071426;color:#f8fafc}a{color:inherit}.shell{width:min(1080px,calc(100% - 32px));margin:auto;padding:34px 0 54px}.top{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:48px}.brand{display:flex;align-items:center;gap:10px;font-weight:800;text-decoration:none}.mark{border:1px solid #5eead4;border-radius:12px;padding:7px 9px;color:#5eead4}.nav{display:flex;gap:16px;flex-wrap:wrap;color:#cbd5e1}.nav a{text-decoration:none}.hero{text-align:center;max-width:820px;margin:auto}.eyebrow{color:#94a3b8;margin:10px 0}.hero h1{font-size:clamp(2rem,7vw,4.2rem);margin:0}.lead{color:#bdc8d8;line-height:1.85;font-size:1.08rem}.projects{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;margin:46px 0}.card{position:relative;display:block;min-height:300px;padding:32px;border:1px solid #334155;border-radius:30px;background:linear-gradient(145deg,rgba(12,32,57,.95),rgba(7,20,38,.96));color:inherit;text-decoration:none;box-shadow:0 20px 60px #0004}.card.purple{background:linear-gradient(145deg,#35274c,#08192b 70%)}.card.warm{background:linear-gradient(145deg,#3b3430,#08192b 70%)}.icon{display:inline-grid;place-items:center;width:70px;height:70px;border-radius:20px;background:#ffffff12;overflow:hidden}.project-logo{display:block;width:100%;height:100%;object-fit:cover}.wallet-logo{background:#fff;object-fit:contain;padding:5px}.arrow{position:absolute;left:32px;top:40px;font-size:1.6rem}.card h2{font-size:2rem;margin:58px 0 14px}.card p,.muted{color:#bdc8d8;line-height:1.75}.domain{display:block;color:#dbe5f2;margin-top:22px;direction:ltr;text-align:right}.content{border:1px solid #25364d;border-radius:30px;padding:34px;background:#07172acc;margin:26px 0}.content h2{font-size:1.65rem;margin-top:0}.content h3{margin-top:30px}.content p,.content li{color:#c7d2e0;line-height:1.9}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.step{padding:22px;border-radius:20px;background:#ffffff08;border:1px solid #25364d}.step b{display:block;margin-bottom:8px;color:#fff}.cta{display:inline-block;margin-top:12px;padding:13px 20px;border-radius:14px;background:#0c79d8;text-decoration:none;font-weight:700}.footer-links{display:flex;justify-content:center;gap:18px;flex-wrap:wrap;margin-bottom:16px}footer{text-align:center;color:#8492a6;padding:20px 16px 40px}.legal{max-width:850px;margin:auto}.legal h1{font-size:2.5rem}.legal h2{margin-top:32px}.legal p,.legal li{color:#c7d2e0;line-height:1.9}@media(max-width:760px){.top{align-items:flex-start;flex-direction:column}.projects,.steps{grid-template-columns:1fr}.card{min-height:270px}.card h2{margin-top:42px}}
`;

const ION = `<svg class="project-logo" viewBox="0 0 512 512" aria-hidden="true"><defs><linearGradient id="ionbg" x1="56" y1="32" x2="456" y2="480" gradientUnits="userSpaceOnUse"><stop stop-color="#0EA5E9"/><stop offset=".48" stop-color="#2563EB"/><stop offset="1" stop-color="#071B35"/></linearGradient></defs><rect x="24" y="24" width="464" height="464" rx="122" fill="url(#ionbg)"/><circle cx="256" cy="256" r="118" fill="#061A32" fill-opacity=".5" stroke="#E0F2FE" stroke-width="15"/><ellipse cx="256" cy="256" rx="178" ry="74" transform="rotate(-22 256 256)" fill="none" stroke="#7DD3FC" stroke-width="14"/><path d="M256 112v288M112 256h288" stroke="#E0F2FE" stroke-width="13" stroke-linecap="round"/><circle cx="256" cy="256" r="24" fill="#F8FAFC"/><circle cx="409" cy="196" r="18" fill="#34D399" stroke="#ECFDF5" stroke-width="8"/></svg>`;
const ELI = `<svg class="project-logo" viewBox="0 0 64 64" aria-hidden="true"><rect x="2" y="2" width="60" height="60" rx="18" fill="#6D4AA0"/><path d="M32 13c5 7 7 10 7 14a7 7 0 1 1-14 0c0-4 2-7 7-14Z" fill="#F4D7FF"/><path d="M20 35h24l-3 16H23l-3-16Z" fill="#EEE3F7"/><path d="M25 39h14" stroke="#B184D6" stroke-width="3" stroke-linecap="round"/></svg>`;

function layout(title, description, body, canonical="/"){
  return `<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#071426"><title>${title}</title><meta name="description" content="${description}"><link rel="canonical" href="https://hania360.com${canonical}"><style>${CSS}</style></head><body><main class="shell"><div class="top"><a class="brand" href="/"><span class="mark">H360</span><span>Hania360</span></a><nav class="nav" aria-label="ניווט ראשי"><a href="/">בית</a><a href="/about">אודות</a><a href="/privacy">פרטיות</a><a href="/terms">תנאי שימוש</a><a href="/contact">יצירת קשר</a></nav></div>${body}</main><footer><div class="footer-links"><a href="/about">אודות</a><a href="/privacy">מדיניות פרטיות</a><a href="/terms">תנאי שימוש</a><a href="/contact">יצירת קשר</a></div>© 2026 Hania360 · נבנה בישראל</footer></body></html>`;
}

const HOME = layout("Hania360 — טכנולוגיה, יצירה ורעיונות במקום אחד","Hania360 הוא הבית הדיגיטלי של הנחה בכיס, HaniaION ואלינויה — כלים ושירותים שימושיים במקום אחד.",`
<header class="hero"><p class="eyebrow">טכנולוגיה · יצירה · רעיונות</p><h1>כל הפרויקטים במקום אחד</h1><p class="lead">Hania360 מרכז פרויקטים דיגיטליים שנבנו כדי לפתור צרכים אמיתיים: לחסוך כסף לפני קנייה, לעבוד עם נתוני GPS ויונוספירה, ולגלות חוויות יצירה. כל פרויקט פועל כשירות עצמאי, והעמוד הזה מסביר מה הוא מציע ולאן ממשיכים.</p></header>
<section class="projects" aria-label="הפרויקטים של Hania360">
<a class="card" href="https://gps.hania360.com/"><span class="icon">${ION}</span><span class="arrow">←</span><h2>HaniaION</h2><p>מערכת לחישובי GPS ונתוני יונוספירה, בדיקות והתראות. מיועדת לגישה נוחה לנתונים ולכלים ממחשב או מטלפון.</p><span class="domain">gps.hania360.com</span></a>
<a class="card purple" href="https://elinoya.hania360.com/"><span class="icon">${ELI}</span><span class="arrow">←</span><h2>אלינויה</h2><p>סדנאות בוטיק ליצירה והשראה, ובהן עבודה עם בטון פולימרי ונרות מעוצבים. באתר ניתן להכיר את הסדנאות ולבדוק מועדים.</p><span class="domain">elinoya.hania360.com</span></a>
<a class="card warm" href="https://save.hania360.com/"><span class="icon"><img class="project-logo wallet-logo" src="https://save.hania360.com/icons/icon-192.png" alt=""></span><span class="arrow">←</span><h2>הנחה בכיס</h2><p>כלי שמרכז הטבות, כרטיסים, שוברים וקאשבק כדי לעזור לבדוק מה משתלם לפני התשלום ולרכז את אפשרויות החיסכון במקום אחד.</p><span class="domain">save.hania360.com</span></a>
</section>
<section class="content"><h2>הנחה בכיס — למצוא את החיסכון לפני שמשלמים</h2><p>כשלאותה חנות יש הטבות בכמה מועדונים, כרטיסי אשראי, שוברים או שירותי קאשבק, קל לפספס את האפשרות המשתלמת. הנחה בכיס נועד לצמצם את החיפוש הזה: בוחרים חנות וסכום קנייה, בודקים את האפשרויות הרלוונטיות ומקבלים דרך ברורה להמשיך.</p><div class="steps"><div class="step"><b>1. מחפשים חנות</b><span class="muted">מאתרים את בית העסק במאגר ומזינים את סכום הקנייה.</span></div><div class="step"><b>2. משווים אפשרויות</b><span class="muted">המערכת מרכזת הטבות רלוונטיות ומציגה אפשרות מובילה וחלופות כשישנן.</span></div><div class="step"><b>3. משלמים ומעדכנים</b><span class="muted">ממשיכים לאמצעי המתאים וניתן לעדכן את החיסכון לאחר התשלום.</span></div></div><p>המערכת כוללת גם ארנק לשוברים דיגיטליים, כדי שלא יהיה צורך לשמור קודים והודעות במקומות שונים. מידע על הטבות עשוי להשתנות, ולכן לפני רכישה חשוב לבדוק גם את התנאים העדכניים של הגוף שמעניק את ההטבה.</p><a class="cta" href="https://save.hania360.com/">כניסה להנחה בכיס</a></section>
<section class="content"><h2>מה הערך של Hania360?</h2><p>המטרה של Hania360 היא לא להיות עמוד קישורים בלבד. זהו בית לפרויקטים עצמאיים עם שימוש מעשי: HaniaION מרכז כלים טכנולוגיים בתחום GPS והיונוספירה; אלינויה מחברת בין מידע, הרשמה וחוויית יצירה; והנחה בכיס מרכז מידע וכלים לקבלת החלטה לפני תשלום. אנחנו ממשיכים לשפר את המוצרים, את נגישות המידע ואת חוויית השימוש בהתאם לצרכים שעולים מהשטח.</p><h3>שקיפות</h3><p>בחלק מהשירותים עשויים להופיע קישורי שותפים או פרסום. כאשר קישור עשוי להניב עמלה, המטרה היא לשמור על גילוי נאות ולאפשר למשתמש להבין זאת. קבלת עמלה אינה משנה את המחיר למשתמש ואינה מחליפה בדיקה עצמאית של תנאי ההטבה.</p></section>
`,"/");

const ABOUT = layout("אודות Hania360","מידע על Hania360 והפרויקטים הנחה בכיס, HaniaION ואלינויה.",`<article class="legal"><h1>אודות Hania360</h1><p>Hania360 הוא בית דיגיטלי לפרויקטים שימושיים בתחומי טכנולוגיה, חיסכון ויצירה. הרעיון המשותף הוא לקחת מידע או תהליך מפוזר ולהפוך אותו לחוויה פשוטה וברורה יותר.</p><h2>הפרויקטים</h2><p><strong>הנחה בכיס</strong> מסייע לרכז ולבדוק אפשרויות חיסכון לפני תשלום, לרבות הטבות, כרטיסים, שוברים וקאשבק. <strong>HaniaION</strong> מספק כלים הקשורים ל-GPS ולנתוני יונוספירה. <strong>אלינויה</strong> הוא אתר לסדנאות בוטיק ליצירה והשראה.</p><h2>איך אנחנו עובדים</h2><p>אנחנו שואפים להציג מידע ברור, שימושי ונגיש. מידע מסחרי והטבות עשויים להשתנות אצל הספקים עצמם, ולכן התנאים הסופיים של הגוף המציע הם הקובעים. כאשר נעשה שימוש בקישור שותף, אנו שואפים להציג גילוי נאות.</p></article>`,"/about");

const PRIVACY = layout("מדיניות פרטיות — Hania360","מדיניות הפרטיות של Hania360.",`<article class="legal"><h1>מדיניות פרטיות</h1><p>עודכן לאחרונה: 1 באוקטובר 2026.</p><p>Hania360 מכבד את פרטיות המשתמשים. דף הבית עשוי לאסוף מידע טכני בסיסי הנוצר בעת גלישה, כגון סוג מכשיר, דפדפן, עמודים שנצפו ונתוני שימוש מצרפיים, כאשר מופעלים שירותי מדידה או אבטחה.</p><h2>שירותים חיצוניים</h2><p>האתר עשוי להשתמש בשירותי תשתית, אבטחה, מדידה ופרסום של צדדים שלישיים. שירותים אלה עשויים להשתמש בעוגיות או בטכנולוגיות דומות בהתאם למדיניות שלהם ולהסכמות הנדרשות. פרויקטים שאליהם עוברים מתת-הדומיין עשויים להפעיל מדיניות פרטיות נוספת משלהם.</p><h2>פרסום וקישורי שותפים</h2><p>בעתיד עשוי להופיע באתר פרסום, לרבות באמצעות Google AdSense. שירותי פרסום עשויים להשתמש בעוגיות לצורך הצגת מודעות ומדידה, בכפוף לדין ולהגדרות ההסכמה הרלוונטיות. בחלק מהעמודים עשויים להופיע קישורי שותפים שיכולים להניב עמלה.</p><h2>יצירת קשר</h2><p>לשאלות בנושא פרטיות ניתן לפנות דרך עמוד <a href="/contact">יצירת הקשר</a>.</p></article>`,"/privacy");

const TERMS = layout("תנאי שימוש — Hania360","תנאי השימוש באתר Hania360.",`<article class="legal"><h1>תנאי שימוש</h1><p>השימוש ב-Hania360 ובקישורים ממנו נעשה לצורכי מידע ושימוש בשירותים המוצעים. אנו פועלים לשמור על מידע תקין ועדכני, אך אין התחייבות לכך שכל מידע, הטבה, מחיר, זמינות או תנאי מסחרי יישארו ללא שינוי.</p><h2>הטבות וחיסכון</h2><p>מידע על הטבות, כרטיסים, שוברים וקאשבק אינו מהווה התחייבות של בית העסק או הגוף המעניק את ההטבה. לפני ביצוע עסקה יש לבדוק את התנאים העדכניים אצל הספק הרלוונטי.</p><h2>קישורים חיצוניים</h2><p>Hania360 מקשר לשירותים ותתי-דומיינים נוספים. השימוש בהם עשוי להיות כפוף לתנאים ולמדיניות נוספים. קישורי שותפים עשויים להניב עמלה לבעל האתר ללא תוספת מחיר למשתמש.</p><h2>שינויים</h2><p>ניתן לעדכן את האתר, השירותים והתנאים מעת לעת כדי לשפר את המוצרים ולהתאים אותם לשינויים טכנולוגיים או משפטיים.</p></article>`,"/terms");

const CONTACT = layout("יצירת קשר — Hania360","דרכי יצירת קשר בנוגע ל-Hania360 ולפרויקטים.",`<article class="legal"><h1>יצירת קשר</h1><p>מצאתם מידע שדורש תיקון, קישור שלא עובד או שיש לכם שאלה לגבי אחד מפרויקטי Hania360? אפשר לפנות דרך ערוצי יצירת הקשר המופיעים בתוך השירות הרלוונטי.</p><h2>לאיזה שירות לפנות?</h2><p>בנושאי הטבות, שוברים וקאשבק היכנסו ל<a href="https://save.hania360.com/">הנחה בכיס</a>. בנושאי GPS ויונוספירה היכנסו ל<a href="https://gps.hania360.com/">HaniaION</a>. בנושאי סדנאות והרשמה היכנסו ל<a href="https://elinoya.hania360.com/">אלינויה</a>.</p><p>כך הפנייה מגיעה להקשר המתאים, יחד עם המידע העדכני של אותו שירות.</p></article>`,"/contact");

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const pages = {"/":HOME,"/index.html":HOME,"/about":ABOUT,"/privacy":PRIVACY,"/terms":TERMS,"/contact":CONTACT};
    if (url.pathname === "/robots.txt") return new Response("User-agent: *\nAllow: /\nSitemap: https://hania360.com/sitemap.xml\n",{headers:{"content-type":"text/plain; charset=utf-8"}});
    if (url.pathname === "/sitemap.xml") {
      const paths=["","about","privacy","terms","contact"];
      const xml='<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+paths.map(p=>'<url><loc>https://hania360.com/'+p+'</loc></url>').join("")+'</urlset>';
      return new Response(xml,{headers:{"content-type":"application/xml; charset=utf-8"}});
    }
    const page=pages[url.pathname];
    if (!page) return new Response("Not found",{status:404,headers:{"content-type":"text/plain; charset=utf-8"}});
    return new Response(page,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"public, max-age=300","x-content-type-options":"nosniff","referrer-policy":"strict-origin-when-cross-origin"}});
  }
};
